### ISSUE TITLE
Him

### ISSUE THREAD

**Issue by JezebellaJess** [green-api/whatsapp-api-client-python#60]

**Comment by Alunicstar** [comment]
response = greenAPI.sending.sendMessage("11001234567@c.us", "Message text") print(response.data)

**Comment by AknurKh** [comment]
Hello!
You need to use receiver's WhatsApp number instead of 11001234567

The format of the personal chat Id is formed according to the template [00000000000@c.us](mailto:00000000000@c.us), where it is required to use the recipient's phone number instead of zeros00000000000. The telephone number must be entered in full, with the country code and without spaces

Information about group chat id you can find in our [article](https://green-api.com/en/docs/api/chat-id/#gus)
